### ISSUE TITLE
Подтягивает старый ip при запуске thing

### ISSUE THREAD

**Issue by d51x** [d51x/org.openhab.binding.yandexstation#17]
При создании thing в конфиг сохраняется ip адрес колонки, далее он используется постоянно при коннекте к колонке.
Случилось так, что в конфиг прописался адрес 169.254.79.198 и после этого биндинг к колонке не подключется, хотя колонка от роутера получила корректный ip и на ней есть интернет.

Если создать новый thing для колонки, то он подключается к колонке и имеет корректный IP.

Нужно переделать механизм получения/обновления и хранения ip колонки

**Comment by dakhar** [comment]
Подтверждаю проблему. Приходится использовать статический IP, но фича полезная.
